spring:
  profiles:
    active:
    - dev
---
server:
  port: 9101
spring:
  profiles: dev
  application: 
    name: query-server

spring:
   security:
      basic:
         enabled: true
   user:
      name: user
      password: hskpass


eureka_hostname1: localhost:8881
eureka_hostname2: localhost:8882
eureka_hostname3: localhost:8883

eureka: 
  client:
    service-url:
      defaultZone: http://user:hskpass@${eureka_hostname1}/eureka/
    healthcheck:
         enabled: true
  instance:
     preferIpAddress: true
     lease-renewal-interval-in-seconds: 5
     lease-expiration-duration-in-seconds: 15
---
server:
  port: 8102
spring:
  profiles: beta
  application: 
    name: microcloud-config-client
eureka: 
  client:
    service-url:
      defaultZone: http://edmin:studyjava@eureka-beta.com:7001/eureka