spring:
  application:
    name: gateway
zuul:
  ignored-services:
    "*"
  routes:
    global:
      path: /timert/**
      serviceId: usercenter #此处配置服务ID无效，会被filter自动重定向
#    MyOrder:
#      path: /order/**
#      serviceId: order
#      #本服务忽略的报文头
#      sensitiveHeaders:
#    MyUserCenter:
#      path: /uc/**
#      serviceId: usercenter
#    MyPay:
#      path: /pay/**
#      serviceId: pay
#    MyBalance:
#      path: /balance/**
#      serviceId: balance
#    MyManager:
#      path: /manager/**
#      serviceId: manager
  #正则的方式过滤掉某些地址
  ignored-patterns:
  #全局忽略的敏感头
  sensitive-headers:


server:
  paths:
    usercenter: #serverId
      loginNoPass: /login/nopass      #serverCode及对应的实际path
    order: #serverId
      ordertest: /test/str      #serverCode及对应的实际path
      orderconfig: /test/testConfig
    pay:
      paytest: /test/str
      payback: /test/fallback