spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jyj1987/myself
          username: jyj1987
          password: Wmj880608
          basedir: F:\basedir
          default-label: master
          search-paths: /config/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8101
