spring:
  application:
    name: pay
  jpa:
    database: mysql
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.137.103:3306/springcloud?useSSL=false&characterEncoding=utf-8
  cloud:
    stream:
      bindings:
        output:
          destination: pay-default
          group: pay
          content-type: application/json
        input:
          destination: pay-default
  redis:
    host: 192.168.137.100
    port: 6379
    timeout: 3000
    password:
