spring:
  application:
    name: order
#  cloud:
#    stream:
#      bindings:
#        output:
#          destination: order-default
#          group: order
#          content-type: application/json
#        input:
#          destination: order-default
#        orderInput:
#          destination: order-my
#        orderOutput:
#          destination: order-my
#          group: order-my
#          content-type: application/json
