spring:
  rabbitmq:
    host: 192.168.137.100
    port: 5672
    username: guest
    password: guest
feign:
  hystrix:
    enabled: true
  compression:
      request:
        mime-types: text/xml,application/xml,application/xml
        min-request-size: 2048
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 1000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
