spring:
  redis:
    cluster:
      # 各 Redis 节点信息
      #nodes: 39.104.87.147:9001,39.104.87.147:9002,39.104.87.147:9003,39.104.87.147:9004,39.104.87.147:9005,39.104.87.147:9006
      nodes: 172.17.0.9:9001,172.17.0.9:9002,172.17.0.9:9003,172.17.0.9:9004,172.17.0.9:9005,172.17.0.9:9006
      # 执行命令超时时间
      command-timeout: 15000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true
  rabbitmq:
    host: 172.17.0.9
    port: 5672
    username: admin
    password: Szkj123!@#
    listener:
      simple:
        acknowledge-mode: manual
feign:
  hystrix:
    enabled: true
  compression:
    request:
      mime-types: text/xml,application/xml,application/xml
      min-request-size: 2048
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 1000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1300000   #大于等于 (ribbon.ReadTimeout+ribbon.ConnectTimeout)*2
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
